### ISSUE TITLE
rspec not found when using the rails generator

### ISSUE THREAD

**Issue by ekampp** [trailblazer/cells-rails#11]
Hi. 

Running `bundle exec rails generate cell Xyz` fails to generate a spec for the cell.

```
create  app/cells/bid_cell.rb
create  app/cells/bid/show.slim
error  rspec [not found]
```

  * cells (4.1.4)
  * cells-rails (0.0.6)
  * cells-slim (0.0.5)
  * rspec-core (3.6.0.beta1)
  * rspec-expectations (3.6.0.beta1)
  * rspec-mocks (3.6.0.beta1)
  * rspec-rails (3.6.0.beta1)
  * rspec-support (3.6.0.beta1)

**Comment by seuros** [comment]
add `gem "rspec-cells"`

**Comment by ekampp** [comment]
NIce. Thanks. Was that in the readme? I clearly missed that.
