### ISSUE TITLE
Ruby 2.4 warning about delegating a private/protected method `protect_against_forgery?`

### ISSUE THREAD

**Issue by RKushnir** [trailblazer/cells-rails#23]
`ViewModel#protect_against_forgery?` is delegated to the parent controller here:
https://github.com/trailblazer/cells-rails/blob/a0816159225cff22acdbc27a690cea16b67ae1c3/lib/cell/rails.rb#L50
Ruby 2.4 changes the behavior of `Forwardable` to issue a warning whenever a protected or private method is called via delegation. See https://bugs.ruby-lang.org/issues/12782
Thus, rendering a form inside a cell now prints:
```ruby
/Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionview-5.0.2/lib/action_view/helpers/url_helper.rb:590:in `token_tag':
#<Module:0x007f899ae87aa8>#protect_against_forgery? at /Users/user/.rbenv/versions/2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method UsersController#protect_against_forgery?
```

**Comment by zavan** [comment]
A simple, but fragile, hack to avoid these warnings is to override and manually delegate these methods in the cell (I actually have a cell that all other cells inherit from, so that's where I'm doing this):

```ruby
def protect_against_forgery?
  controller.send(:protect_against_forgery?)
end

def form_authenticity_token(*args)
  controller.send(:form_authenticity_token, *args)
end
```

**Comment by zavan** [comment]
@rafaelfranca Shouldn't Rails make those methods public, since we can render templates other ways than with ActionView (as is our case)?

**Comment by RKushnir** [comment]
@zavan Or simpler: `public :protect_against_forgery?`

**Comment by zavan** [comment]
@RKushnir this didn't work for me.

**Comment by RKushnir** [comment]
@zavan Sorry, I meant that in the controller.

**Comment by zavan** [comment]
@RKushnir Now it does, much better. Thanks!

**Comment by rafaelfranca** [comment]
We can't make those methods public in a controller because every public method is a valid action so you could be exposing those methods to a web request depending on your routes.

**Comment by zavan** [comment]
@rafaelfranca I see. Thanks for the answer.

**Comment by rafaelfranca** [comment]
> A simple, but fragile, hack to avoid these warnings is to override and manually delegate these methods in the cell (I actually have a cell that all other cells inherit from, so that's where I'm doing this)

This is how it is implemented in rails today.

**Comment by seanfcarroll** [comment]
So this won't be fixed? It's causing a lot of grief with my tests...

**Comment by georgemillo** [comment]
I'll look into it next week.

**Comment by georgemillo** [comment]
Oops, I meant to post a comment on here but I accidentally posted it [on the PR]. Ahem, to repeat: This should now be fixed on `master`. Let me know if you have any further issues.
