### ISSUE TITLE
default_url_options is not delegated to the parent_controller

### ISSUE THREAD

**Issue by anton-yordanov** [trailblazer/cells-rails#38]
I think that default_url_options should be delegated to the parent controller by default
https://github.com/trailblazer/cells-rails/blob/bac2715bafbd13de2c1da2936bd82566516d444b/lib/cell/rails.rb#L48
It is something which is widely used in Rails and related with the  `url_options`

**Comment by apotonick** [comment]
I could swear I added this... 7 years ago! Hey @georgemillo how are you feeling about this? :beers:
