### ISSUE TITLE
API to turn on/off cache?

### ISSUE THREAD

**Issue by saiqulhaq** [trailblazer/cells-rails#43]
Hi

I am wondering is there any way to activate cache conditionally?  
let say when developing a `Cell` in development server 

currently I do this little hack for few months, might be there is better way

```ruby
module Trailblazer

  class Cell
    class << self
      alias_method :origin_cache, :cache

      def cache(state, *args, &block)
        return unless CacheSetting.enabled?
        origin_cache(state, *args, &block)
      end
    end
  end

end
```

**Comment by apotonick** [comment]
This method is your friend: https://github.com/trailblazer/cells-rails/blob/master/lib/cell/rails.rb#L62

**Comment by saiqulhaq** [comment]
OK thanks, it works 👍
