### ISSUE TITLE
Cells-rails defines crashing request method when used without parent controller

### ISSUE THREAD

**Issue by kreintjes** [trailblazer/cells-rails#50]
I have cells-rails included in my project and I have a Cell which sometimes is rendered from a view/controller, and sometimes from a model (in a background job). In this cell I am using the high_chart helper from the [lazy_high_charts](https://github.com/michelson/lazy_high_charts) gem. This gem does a check somewhere if there is an xhr request going on, and uses the request object for that: https://github.com/michelson/lazy_high_charts/blob/f7d4d1614816c98d81d9d7d387d4b6e0a9901d05/lib/lazy_high_charts/layout_helper.rb#L76

The cell renders perfectly from a view/contrroller. However, rendering the cell from the model fails, because request delegates to parent_controller, which isn't available at that point. Full error and backtrace:

```
NoMethodError: undefined method `[]' for nil:NilClass
/gems/2.4.0/gems/cells-rails-0.0.8/lib/cell/rails.rb:58:in `parent_controller'
/2.4.0/forwardable.rb:223:in `request'
/gems/2.4.0/bundler/gems/lazy_high_charts-c21849e7e1f4/lib/lazy_high_charts/layout_helper.rb:77:in `request_is_xhr?'
/gems/2.4.0/bundler/gems/lazy_high_charts-c21849e7e1f4/lib/lazy_high_charts/layout_helper.rb:95:in `encapsulate_js'
/gems/2.4.0/bundler/gems/lazy_high_charts-c21849e7e1f4/lib/lazy_high_charts/layout_helper.rb:40:in `build_html_output'
/gems/2.4.0/bundler/gems/lazy_high_charts-c21849e7e1f4/lib/lazy_high_charts/layout_helper.rb:24:in `high_graph'
/gems/2.4.0/bundler/gems/lazy_high_charts-c21849e7e1f4/lib/lazy_high_charts/layout_helper.rb:10:in `high_chart'
app/cells/analysis/chart.slim:2:in `block in singleton class'
app/cells/analysis/chart.slim:-2:in `instance_eval'
app/cells/analysis/chart.slim:-2:in `singleton class'
app/cells/analysis/chart.slim:-5:in `__tilt_70304215070660'
/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
/gems/2.4.0/gems/cells-4.1.7/lib/cell/view_model.rb:118:in `render_template'
/gems/2.4.0/gems/cells-slim-0.0.5/lib/cell/slim.rb:8:in `render_template'
/gems/2.4.0/gems/cells-4.1.7/lib/cell/view_model.rb:110:in `render_to_string'
/gems/2.4.0/gems/cells-4.1.7/lib/cell/layout.rb:23:in `render_to_string'
/gems/2.4.0/gems/cells-4.1.7/lib/cell/view_model.rb:104:in `render'
app/cells/analysis_cell.rb:189:in `chart'
```

The error happens, because context isn't set, thus it can't determine the parent_controller. I could give a context when calling the cell, i.e. `context: { controller: :some_controller }`, but that doesn't fix the error. Now I get a `NoMethodError: undefined method `request' for :some_controller:Symbol`. I could build a fake controller setting request to nil like `context: { controller: OpenStruct.new(request: nil) }` which works, but feels very hacky.

I think the problem is that cells-rails defines request (which crashes when calling it), tricking lazy_high_charts into thinking there is an actual request going on, while there isn't. I can perfectly use lazy_high_charts from within a model/job or even just in a Rails console (no controller/request there), but not when I use it within a cell.

@michelson you want to pitch in as well?

Versions:
- Ruby 2.4.1
- Rails 5.0.4
- Cells 4.1.7
- Cells-Rails 0.0.8
- Lazy_high_charts 1.5.7

**Comment by apotonick** [comment]
That is not a Cells bug, but a problem in the chart gem you're using. It requires a controller instance with a `#request` method. The fact you have to pass this into the cell is not hacky but a clear indicator of a shitty dependency situation in the Rails helpers and that gem that relies on global variables such as the request object. Anyway, Cells are stupid, if your helpers need all those dependencies, you need to pass them in there. :beers:

**Comment by kreintjes** [comment]
Thanks for your response @apotonick. The helper I'm using doesn't require a controller or request. It works perfectly without controller or request, e.g. from a Ruby console. It only checks if there is a request and if so behaves a bit differently (see https://github.com/michelson/lazy_high_charts/blob/f7d4d1614816c98d81d9d7d387d4b6e0a9901d05/lib/lazy_high_charts/layout_helper.rb#L76). So it should render perfectly from within an environment without controller or request, such as from a cell.

The problem however, is that cells-rails does define the request method, but when calling it crashes since it does not have a controller. I think the chart gem I'm using can't do much different, it already checks if there is an request before trying to use it. I believe cells-rails wrongly defines request (while we aren't in a controller environment), tricking the charts gem into thinking it's there, using it and then crashing. The only thing the chart gem could do to fix this problem, is wrapping the whole request calling in a rescue block and then ignoring the triggered exception, but that wouldn't be ideal.

**Comment by apotonick** [comment]
Thanks for explaining @kreintjes - I've checked the gem and I am a bit shocked about the code. A gem that constantly checks for `respond_to?` or `defined?` and then magically changes behavior is just not right. It's very typical for Rails-focused libraries that copy patterns from Rails core, but that doesn't have to mean it's good style. :angel: 

Since there's no strict definition of the helper API in Rails (e.g. something like "for this and that behavior, you need to pass in a `request` object") it is impossible to support all gems and their implicit dependencies. The chart gem, as an example, shouldn't magically figure out things based on the absence or presence of a `request` method, I mean how messy is that? It should provide different methods for differing behavior or at least an explicit argument to specify that.

I'm sorry this is no real help for you, but you can always `undef` the request method.

**Comment by michelson** [comment]
Hi there. 
The chart gem is well tested and works on rails but in others ruby frameworks too. If you are in the rails context and in a controller context it's perfectly valid thing to use the request object. But if your gem redefines the request of course other gems that relies on it could fail.

I've not used cells before, so can't help much here. maybe @kreintjes could came up with an example repo ?? I could look this a little further

**Comment by pjar** [comment]
@apotonick You gave no-answer there. The cells-rails bridge should not exist then if you feel that rails should not really exist and rhr all there is bad and ugly. Now I'm going back to decode what the heck is going on with the same issue in my case but without chart gem as cell-rails is  just taking for granted that everyone should code in the one 'right' way.

**Comment by apotonick** [comment]
Hey @pjar there are `view_components` now backed by a multi-million dollar company, it's much better maintained as they have one person working full time on it, don't waste your time with our unprofessional DIY framework. :wink:
