### ISSUE TITLE
Rails 6.0.2.1 uses `::ActionDispatch::TestRequest.create`

### ISSUE THREAD

**Issue by duleorlovic** [trailblazer/cells-rails#57]
In my Rails 6.0.2.1 app, when I want to test 

```
# test/concepts/thing/cell_test.rb
class ThingCellTest < Cell::TestCase
  controller ThingsController

  test 'success' do
    trb = Thing::Operation::Create.(params: { name: 'Trailblazer' })
    rails = Thing::Operation::Create.(params: { name: 'Rails' })
    html = concept('thing/cell', collection: [trb, rails], last: rails)
    assert true
  end
end
```
it gives me an error
```
NameError: uninitialized constant ActionController::TestRequest
    cells-rails (0.1.0) lib/cell/rails/testing.rb:22:in `action_controller_test_request'
```
I found that in Rails 6.0.2.1 instead of [::ActionController::TestRequest.create(controller_class)](https://github.com/trailblazer/cells-rails/blob/901d2d663ce075bf89c439019dbf2e4a9801d718/lib/cell/rails/testing.rb#L22) we need to use
```
::ActionDispatch::TestRequest.create
```

I would like to fix this and to add another if statement for RAILS_6_0_2 but I can not run tests for this gem.
I got an error.
```
export RAILS_VERSION=5.2
bundle
rake

Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server
```

**Comment by apotonick** [comment]
Thank you @duleorlovic! I think @seuros can help here?

**Comment by seuros** [comment]
I will submit a fix asap.

**Comment by duleorlovic** [comment]
@seuros can you also update the README with instructions how to run the tests ?

**Comment by seuros** [comment]
@duleorlovic  can you try master ?

**Comment by duleorlovic** [comment]
Sorry, but I do not see any code change in this repository. Have you pushed the changes ?

**Comment by seuros** [comment]
@duleorlovic, the code was already updated but not released.

I was working in my rails 6 app.

if it not working, can you author a small repo with a sample app  and share it. I will fix it for you and release the new version.

**Comment by duleorlovic** [comment]
Yea, sorry, probably I was missing `concept().to_s` and I start debugging and wrongly assumed that we need to upgrade for Rails 6.
Here is example of working test https://github.com/duleorlovic/gemgem-trb-rails-6/blob/master/test/concepts/thing/cell_test.rb#L12
Next time I will double check my assumptions
