### ISSUE TITLE
Rails 6.1 has changed translation shortcut path lookup

### ISSUE THREAD

**Issue by samstickland** [trailblazer/cells-rails#60]
Previously it was looking for `@virtual_path`, but now it looks for `@current_template&.virtual_path` and in cell `@current_template` is `nil`. This breaks `Cell::Translation`

I haven't yet found how `@current_template` is set.

**Comment by seuros** [comment]
What versions are you using ?

**Comment by samstickland** [comment]
I'm away from my computer right now, but it will be the very latest cells
and cells-rails releases, Ruby 2.7.2 and Rails 6.1.

**Comment by samstickland** [comment]
Here's a fuller answer:

```
 $grep cells Gemfile.lock
    cells (4.1.7)
    cells-erb (0.1.0)
      cells (~> 4.0)
    cells-rails (0.1.3)
      cells (>= 4.1.6, < 5.0.0)
    cells-slim (0.1.1)
      cells (>= 4.0.1, < 6.0.0)
    rspec-cells (0.3.5)
      cells (>= 4.0.0, < 6.0.0)
    trailblazer-cells (0.0.3)
      cells (>= 4.1.0.rc1, < 5.0.0)
```

**Comment by samstickland** [comment]
This kind of approach seems to fix the issue:

```diff
diff --git a/lib/cell/translation.rb b/lib/cell/translation.rb
index 4c1201e..d85b369 100644
--- a/lib/cell/translation.rb
+++ b/lib/cell/translation.rb
@@ -4,9 +4,12 @@ def self.included(includer)
     includer.inheritable_attr :translation_path
   end

+  Template = Struct.new(:virtual_path)
+
   def initialize(*)
     super
-     @virtual_path = translation_path
+    @current_template = Template.new(translation_path)
   end

 private
```

It would need tests, and also checks to only set `@current_template` on Rails 6.1+.

These changes in Rails are likely to be part of the pluggable component system that was added for Github components?

**Comment by samstickland** [comment]
Hmm.. I'm working on a PR to address this issue but I've having trouble making the tests fail correctly for 6.1. Currently everything is passing on my PR without the fix added yet :/

**Comment by apotonick** [comment]
Hey cool, how did you create that diff snippet from the second to last answer?

**Comment by apotonick** [comment]
@samstickland Could you point me to the Rails code location where `@virtual_path` is being referenced? :beer:

**Comment by samstickland** [comment]
> Hey cool, how did you create that diff snippet from the second to last comment?

@apotonick  When you open with the three `'''` you can append a file type like `'''ruby` or `'''diff`

So it turns out that I no longer have this problem on Rails 6.1.3, so something changed in one the minor releases I think. I am investigating.

**Comment by samstickland** [comment]
Yep.. It was broken in 6.1.0 but working in 6.1.1. This was the failing test:

```
../Users/samuelstickland/.gem/ruby/2.7.2/gems/actionview-6.1.0/lib/action_view/helpers/translation_helper.rb:134: warning: instance variable @current_template not initialized
E

Error:
TranslationTest#test_0002_anonymous:
RuntimeError: Cannot use t(".greeting") shortcut because path is not available
    test/translation_test.rb:10:in `greet_relative'
    test/translation_test.rb:28:in `block in <class:TranslationTest>'
```

**Comment by samstickland** [comment]
I'm putting what we were using as work around on 6.0.0 for reference there, in case this issue comes up again.

```ruby
module Cell
  module Translation
    def self.included(includer)
      super
      includer.inheritable_attr :translation_path
    end

    Template = Struct.new(:virtual_path)

    def initialize(*)
      super
      @virtual_path = translation_path
      @current_template = Template.new(translation_path)
    end

  private
    # If you override this to change this path, please report it on the trailblazer/chat gitter channel,
    # so we can find out best practices.
    def translation_path
      self.class.translation_path or self.class.controller_path.gsub("/", ".")
    end
  end
end
```

**Comment by samstickland** [comment]
@apotonick I found this PR which I believe fixed the problem in Rails https://github.com/rails/rails/pull/40981 so I'm closing this issue.
